---

- hosts: 31.220.111.56
  become_user: root
  become_method: sudo
  become: yes
  tasks: 
  - name: update  pkg
    shell:
    with_items:
       - sudo apt-get install python-apt
       - sudo apt-get update
    tags: 
        - 1  
           

  - name: update and upgrade
    shell:
    with_items:
      - sudo apt-get install urpgrade
    tags: 
        - 2 
          
   
  - name: requirement's packages to the geodejango installation
    apt:
      force_apt_get: yes
      pkg: '{{ item }}' 
      state: present
    with_items:
        - python3.6
        - virtualenv
        - python-dev
        - libpq-dev
        - build-essential
        - git
        - make 
        - software-properties-common
        - libxml2-dev
        - libxslt-dev
        - python-lxml
        - binutils 
        - libproj-dev
        - gdal-bin 
    tags: 
        - 3

  - name: GEOS
    shell: '{{ item }}'
    with_items:
         - /opt/vp/docs/ wget http://download.osgeo.org/geos/geos-7.1.0beta1.tar.bz2
         - /opt/vp/docs/tar xf geos-3.7.0beta1.tar.bz2
         - /opt/vp/docs/geos-3.7.0beta1/ ./configure
         - /opt/vp/docs/geos-3.7.0beta1/ make 
         - /opt/vp/docs/geos-3.7.0beta1/ sudo make install 
         - /opt/vp/docs/geos-3.7.0beta1/ sudo ldconfig
    tags: 
         - 5
           
  - name: PROJ4
    shell: '{{ item }}'
    with_items:
        - /opt/vp/docs/ wget  http://download.osgeo.org/proj/proj-5.1.0.tar.gz
        - /opt/vp/docs/ wget  http://download.osgeo.org/proj/proj-datumgrid-1.7.tar.gz
        - /opt/vp/docs/tar xzf proj-5.1.0.tar.gz
        - /opt/vp/docs/proj-5.1.0/nad/tar xzf ../../proj-datumgrid-1.7.tar.gz
        - /opt/vp/docs/proj-5.1.0/ ./configure
        - /opt/vp/docs/proj-5.1.0/ make
        - /opt/vp/docs/proj-5.1.0/ sudo make install
        - /opt/vp/docs/proj-5.1.0/ sudo ldconfig
    tags:
         - 6
   
  - name: postgres-10 and postgis
    shell: '{{ item }}'
    with_items:
          - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add 
          - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          - sudo apt-get update
          - sudo apt-get upgrade  
          - sudo apt-get install postgresql-10
          - sudo apt-get install postgresql-client-10
          - sudo apt-get install postgresql-contrib-9.5
          - sudo apt-get install libpq-dev
          - sudo apt-get install postgresql-server-dev-10
          - sudo apt-get install pgadmin4
          - sudo apt-get install postgis
    tags: 
          - 7            
           
  
  - name: pip packages
    shell: '{{ item }}'
    with_items:
          - cd /opt/
          - virtualenv vp -python=python3.6
          - cd vp
          - . bin/activate
          - pip install django
          - pip install psycopg2
    tags: 
          - 4 
          
  
  - name: last steps 
    shell: '{{ item }}'
    with_items:
           - echo "sudo su - postgres | createdb <NAME>  CREATE EXTENSION postgis;  select PostGIG_full_version();"
    tags: 
          - 8 
      